name: Continuous Integration

on: [push]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create Database
      run: |
        mkdir -p database/testing
        touch touch database/testing/db.sqlite

    - name: Codestyle validation with PHP-CS-Fixer
      run: vendor/bin/php-cs-fixer fix --dry-run --diff

    - name: Execute tests via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/testing/db.sqlite
      run: vendor/bin/phpunit --coverage-clover=coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} #required
        file: ./coverage.xml #optional
        fail_ci_if_error: true #optional (default = false)
